### ISSUE TITLE
Clang compilation

### ISSUE THREAD

**Issue by wiluite** [msharov/cwiclo#2]
Hello.
I would like to investigate this software a little bit for myself. Could you look at compilation process with clang once more? I use Linux Mint and clang 7 binary pre-built (downloaded some time ago from LLVM site). I  have got many compilation problems beginning from app.cc. If you would recommend GCC 7+ for sure, ok, I will build a new GCC, but it is just time consuming for me nearest days.
Thanks!
btw.
Are you planning to support Windows functioning in the future, or is this tool linux-only forever?

**Comment by msharov** [comment]
Problems fixed by commit cd16aacd287778759ca30e1aa37c0505fe1f05c6.

These will, of course, recur periodically, since I never use clang for normal development. The resulting binaries are larger and slower, while compilation is no faster than with gcc, so the only reason to use clang is the political one of its license. I do not disagree with that one, so I do intend to fix clang problems at least for the releases.

Windows, on the other hand, I will NEVER support. Microsoft no longer supports Windows either, as of next month, and has for years been actively deprecating all C++ development in favor of C#. Windows will naturally continue to exist for supporting legacy applications, but there is every reason to discourage developing anything new for it.
